language: python
python:
  - "3.6"      
  - "3.7"
  - "3.8"
  - "3.9" 
  - "3.9-dev" 

# install local package
install:
  - pip install -r requirements.txt
  - pip install .

before_script:
- install_cmdstan

# command to run tests
script:
  - pytest