language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch

# install local package
install:
  - pip install -r requirements.txt
  - pip install .

before_script:
- install_cmdstan

# command to run tests
script:
  - pytest